[package]
name = "test-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
mytypeid_macro = { path = "../mytypeid_macro" }
mytypeid_trait = { path = "../mytypeid_trait" }
other_lib = { path = "../other_lib" }

