[package]
name = "mytypeid_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
syn = "2.0.65"
mytypeid_trait = {path = "../mytypeid_trait"}


[lib]
proc-macro = true
